ALTER TABLE `WTS_RADIOLOG` ADD `DIVISIONID` INT( 11 ) NOT NULL AFTER `CHECKEDOUT`;
UPDATE `WTS_RADIOLOG` SET `DIVISIONID` = '600' WHERE 1;
ALTER TABLE `WTS_INVENTORY` ADD `DIVISIONID` INT( 11 ) NOT NULL AFTER `DESCR`;
UPDATE `WTS_INVENTORY` SET `DIVISIONID` = '600' WHERE 1;


--adding Vehicles into inventory
INSERT INTO `PAYROLL`.`WTS_INV_TYPE` (
`IDNUM` ,
`DESCR` ,
`MANUFACTURER` ,
`MODEL`
)
VALUES 
(NULL , 'VEHICLE', 'INTL.HARV', '30ft.32pass bus'),
(NULL , 'VEHICLE', 'FORD', 'CROWN VIC 4DR'),
(NULL , 'VEHICLE', 'HUMMER', 'H1'), 
(NULL , 'VEHICLE', 'KAWASAKI', 'MULE 4WD CART'),
(NULL , 'VEHICLE', 'FORD', 'EXPEDITION'),
(NULL , 'VEHICLE', 'OLDS', 'AURORA 4DR'),
(NULL , 'VEHICLE', 'FORD', 'CLUB WAGON'),
(NULL , 'VEHICLE', 'BARTH', 'COMMAND CENTER'),
(NULL , 'VEHICLE', 'DODGE', 'DAKOTA'),
(NULL , 'VEHICLE', 'DODGE', 'DURANGO'),
(NULL , 'VEHICLE', 'FORD', 'E-350'),
(NULL , 'VEHICLE', 'FORD', 'E-150'),
(NULL , 'VEHICLE', 'FORD', 'EXPLORER'),
(NULL , 'VEHICLE', 'FORD', 'F350'),
(NULL , 'VEHICLE', 'FORD', 'F250'),
(NULL , 'VEHICLE', 'JEEP', 'GRAND CHEROKEE'),
(NULL , 'VEHICLE', 'CHRYSLER', 'MODEL 300 '),
(NULL , 'VEHICLE', 'DODGE', 'RAM TRUCK'),
(NULL , 'VEHICLE', 'GMC', 'SAVANNA'),
(NULL , 'VEHICLE', 'CHEVY', 'TAHOE'),
(NULL , 'VEHICLE', 'FORD', 'TAURUS')
;

ALTER TABLE `WTS_INVENTORY` ADD `VIN` VARCHAR( 50 ) NOT NULL AFTER `TYPE`;
ALTER TABLE `WTS_INVENTORY` ADD `COLOR` VARCHAR( 50 ) NOT NULL AFTER `TYPE`;
ALTER TABLE `WTS_INVENTORY` ADD `YEAR` VARCHAR( 4 ) NOT NULL AFTER `TYPE`;
ALTER TABLE `WTS_INVENTORY` ADD `LICENSE` VARCHAR( 50 ) NOT NULL AFTER `TYPE`;
ALTER TABLE `WTS_INVENTORY` ADD `CAR_NO` VARCHAR( 4 ) NOT NULL AFTER `TYPE`;

--Import Columns
--TYPE, YEAR,	COLOR,	SERIAL_NUM, 	OTHER_SN,	VIN,	LICENSE,	DIVISIONID, 	PRIORITY_TYPE,	IS_ACTIVE, 	QUANTITY, 	QUANTITY_AVAILABLE, 	AUDIT_ID 

UPDATE `WTS_INVENTORY` AS I SET `TYPE`=
(SELECT IDNUM FROM WTS_INV_TYPE AS INV WHERE I.`TYPE` = CONCAT(INV.MANUFACTURER, ' - ', INV.MODEL))   
WHERE 1
and type REGEXP '[0-9]+';

--CREATE MILAGE TABLE
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


CREATE TABLE IF NOT EXISTS `WTS_VEH_MILAGE` (
  `IDNUM` int(11) NOT NULL AUTO_INCREMENT,
  `INV_ID` int(11) NOT NULL,
  `MILAGE` VARCHAR( 15 ) NOT NULL,
  `DATE` date NOT NULL,
  `AUDIT_ID` int(11) NOT NULL,
  `AUDIT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `AUDIT_IP` int(10) unsigned NOT NULL,
  PRIMARY KEY (`IDNUM`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `WTS_VEH_NOTES` (
  `IDNUM` int(11) NOT NULL AUTO_INCREMENT,
  `INV_ID` int(11) NOT NULL,
  `NOTES` varchar(255) NOT NULL,
  `DATE` date NOT NULL,
  `AUDIT_ID` int(11) NOT NULL,
  `AUDIT_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `AUDIT_IP` int(10) unsigned NOT NULL,
  PRIMARY KEY (`IDNUM`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;



